### ISSUE TITLE
Installation ok, keine sinnvollen Antworten auf Anfragen

### ISSUE THREAD

**Issue by MichlW** [tigerxy/OnlineTelefonbuch#12]
Hallo tigerxy,

ich versuche jetzt bereits mehrere Stunden in den zurückliegenden Tagen deine Api für mein Gigaset C610A IP ans laufen zu bekommen. Ich denke, dass mein Setup auf dem Webserver ok ist, leider bekomme ich über den Api-Test keine sinnvollen Ergebnisse und auch das C610H Handset klemmt bei der Suche im Telefonbuch ohne Ergebnisse fest.
Jetzt wende ich mich an dich/euch auf der Suche nach Hinweisen, was ich falsch mache.

Auf dem PHP-fähigen Webserver liegen folgende Files:
![image](https://user-images.githubusercontent.com/49558935/122343367-e9f87780-cf45-11eb-9e40-399fab7e8f07.png)
(im Ordner classes liegen die gleichen drei Dateien wie im Repo-Ordner classes)

Bei Aufruf der api.php im Browser erhalte ich eine XML Antwort:
![image](https://user-images.githubusercontent.com/49558935/122343649-39d73e80-cf46-11eb-8a0f-b451523f714f.png)

Das Ergebnis einer Suche nach "Schmidt" in "Berlin" im Api-Test sieht leider so aus:
![image](https://user-images.githubusercontent.com/49558935/122343167-b289cb00-cf45-11eb-9d95-7d9eb823d089.png)

Fehlt evtl. im Api-Test eine wichtige Eingabe?
Ich hoffe jemand hat eine Idee, wie ich das doch noch ans laufen bringe...
Danke vorab!

**Comment by tigerxy** [comment]
Hey Michl,
hab mir das mal angeschaut und den Fehler behoben. Jetzt spuck die API Ergebnisse aus.
Wenn du weitere Fragen hast, schreib mir einfach! :smiley: 
Schöne Grüße
Roland

**Comment by MichlW** [comment]
Hallo tigerxy,
leider hat sich durch deine Änderung in meiner Installation im Verhalten der Api nichts geändert. Sowohl für suchen nach Name und Stadt, als auch für Suchen nach telefonnummern erhalte ich immer die identische Antwort von der Api:

Suche nach Schmidt in Berlin:
![image](https://user-images.githubusercontent.com/49558935/122609235-f54ebe80-d07d-11eb-98ee-aa0c8c5230ec.png)

Suche nach 08003301000:
![image](https://user-images.githubusercontent.com/49558935/122609137-d0f2e200-d07d-11eb-8879-595d872991c2.png)

Ich weiß nicht mehr, was ich noch ausprobieren soll...
Hast du eine Testinstallation der Api, gegen die ich die Funktion vergleichen kann?
Tätige ich in der Test-Api die korrekten Eingaben, oder fehlt etwas?

Danke!!!

**Comment by tigerxy** [comment]
Hallo Michl,
bei mir klappt das wunderbar:

`GET https://www.*.com/api.php?command=get_list&type=pb&first=1&count=1&limit=1024&hm=08003301000&last=10 HTTP/1.1`

`GET https://www.*.com/api.php?command=get_list&type=pb&first=1&count=1&limit=1024&&ct=Berlin&ln=Schmidt&last=10 HTTP/1.1`

Ich habe das bei Heroku laufen. Kannst dir dort einfach einen kostenlosen Hobby Dyno klicken mit `Deploy to Heroku`. Ich hoffe das hilft dir weiter.

**Comment by MichlW** [comment]
Tatsächlich. Ich hab das jetzt mal bei Heroku ausprobiert und es funktioniert im Browser wie erwartet.
Auf dem Gigaset erhalte ich zwar noch die Meldung "Dienst nicht verfügbar!", aber ich bin jetzt erstmal einen Schritt weiter.
Danke trotzdem!
