### ISSUE TITLE
oertliche.php not found

### ISSUE THREAD

**Issue by VFrontDe** [tigerxy/OnlineTelefonbuch#13]
Hallo,

ich habe das ganze auf meiner Go-Box 100 nach Anleitung eingerichtet und als URL http://.../oertliche.php eingegeben,
In den Logfiles des Containers sehe ich nun, dass /oertliche.php nicht gefunden werden kann, im Browser kommt auch ein Error 404.
Stimmt die Anleitung noch, oder sollte da eigentlich api.php stehen?

Danke und Grüße
Andreas

**Comment by tigerxy** [comment]
Hallo Andreas,

richtig es muss api.php heißen. Der Screenshot ist falsch. Änder ich bei Gelegenheit.

Gruß
Roland

**Comment by VFrontDe** [comment]
Okay, danke.
