### ISSUE TITLE
Test per url und Parameter?

### ISSUE THREAD

**Issue by BigT71** [tigerxy/OnlineTelefonbuch#6]
Hi,

ich habe den Eindruck der zweite Screenshot ist irreführend, dort ist als Serveradresse .../oertliche.php eingetragen statt .../api.php.

Ist es möglich die Funktionalität zu prüfen? Beispielsweise per url mit einer zu aufzulösenden Telefonnummer als Parameter?

**Comment by tigerxy** [comment]
Hab mal eine kleine HTML Seite zum testen der API gebaut. Genaue Doku darüber, wie die API aussehen muss, findet sich in der Gigaset Doku, siehe Link am Ende der Readme.
