### ISSUE TITLE
Abfrage bei "Das Oertliche" nicht mehr korrekt

### ISSUE THREAD

**Issue by tobiaskott** [tigerxy/OnlineTelefonbuch#8]
Hallo,

ich nutze diese Anwendung bereits einige Zeit, jedoch ist mir aufgefallen, dass inzwischen keine Telefonnummern mehr in Namen aufgelöst werden können.

So wie es scheint, wird die Anfrage an das Oertliche zwar korrekt gestellt, jedoch kann die Antwort nicht mehr richtig ausgewertet werden. Womöglich hat sich die Struktur der Seite verändert und daher passt evtl. der reguläre Ausdruck aus oertliche.php:40 nicht mehr.

Über ein entsprechendes Update der Anwendung würde ich mich sehr freuen. Vielen Dank!

**Comment by tigerxy** [comment]
Hallo Tobias,

vielen Dank, dass es dir aufgefallen ist und du dich gemeldet hast! Habe den Fehler gefunden und deine Vermutung war richtig. Das Örtliche hat tatsächlich ein bisschen die Webseite, um ein Leerzeichen, geändert.

Gruß
Roland

**Comment by tobiaskott** [comment]
Hallo Roland,

vielen Dank, jetzt läuft es wieder.

Viele Grüße
Tobias
